### ISSUE TITLE
Macos Dev 搭建失败

### ISSUE THREAD

**Issue by yanickxia** [troyeguo/koodo-reader#87]
## Envirment (操作环境)

| Key(名称)                   | Value(值) |
| --------------------------- | --------- |
| Operating System (操作系统) |     macos  10.15.7      |
| App Version (应用版本)      |      master 分支     |

```
$ node -v
v12.19.0

```
---

## Expected behavior (期望行为)

yarn dev 成功运行

## Current behavior (当前行为)

![image](https://user-images.githubusercontent.com/6848593/108797175-8e386600-75c5-11eb-9c0d-c56ea8d25922.png)

```bash
[1] App threw an error during load
[1] /Users/yanick/codes/tmp/koodo-reader/LICENSE:1
[1] MIT License
[1]     ^^^^^^^
[1] 
[1] SyntaxError: Unexpected identifier
[1]     at Module._compile (internal/modules/cjs/loader.js:815:22)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
[1]     at Module.load (internal/modules/cjs/loader.js:735:32)
[1]     at Module._load (internal/modules/cjs/loader.js:648:12)
[1]     at Module._load (electron/js2c/asar.js:717:26)
[1]     at Function.Module._load (electron/js2c/asar.js:717:26)
[1]     at loadApplicationPackage (/Users/yanick/codes/tmp/koodo-reader/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:109:16)
[1]     at Object.<anonymous> (/Users/yanick/codes/tmp/koodo-reader/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:155:9)
[1]     at Module._compile (internal/modules/cjs/loader.js:880:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
[0] Compiled successfully!
[0] 
[0] You can now view koodo-reader in the browser.
[0] 
[0]   Local:            http://localhost:3000
[0]   On Your Network:  http://10.93.159.94:3000
[0] 
[0] Note that the development build is not optimized.
[0] To create a production build, use yarn build.
[0] 
```

**Comment by yanickxia** [comment]
yarn dist 可以成功，也可以运行。

**Comment by troyeguo** [comment]
貌似是LICENSE这个文件也被当做javascript文件执行了，之前没碰到过这种情况，您可以删除这个文件再试试

**Comment by yanickxia** [comment]
改成这样 

```
 "dev": "concurrently \"cross-env BROWSER=none npm start\" \"wait-on http://localhost:3000/ && nodemon --watch ./main.js --exec electron .\"",

```

就可以~原因未知
